trigger:
- main

pool:
  name: Default

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.13.1'
    addToPath: true
  displayName: 'Use Python 3.13.1'

- powershell: |
    $pythonLocation = Get-Command python | Select-Object -ExpandProperty Source
    Write-Host "Python Location: $pythonLocation"
    python --version
    Write-Host "##vso[task.setvariable variable=PYTHON_PATH]$pythonLocation"
  displayName: 'Get Python Info'

- script: |
    echo "Running Python script..."
    python Change_Parameter.py
  displayName: 'Run Python Script'

- script: |
    echo "Pipeline completed successfully."
  displayName: "Finalize Pipeline"
  condition: always()